"""
Main orchestrator that coordinates all agents using LangGraph
"""

from typing import Dict, Any, Optional
from pathlib import Path
import tempfile
import os

from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate

from agents.planner import PlannerAgent
from agents.backend_generator import BackendGeneratorAgent
from agents.integrator import IntegratorAgent
from agents.packager import PackagerAgent
from utils.github_client import GitHubPublisherAgent
from utils.logger import StreamlitLogger
from utils.llm_manager import LLMFactory, LLMWithFallback

class ProjectState:
    """State object for the LangGraph workflow"""
    def __init__(self):
        self.project_config: Dict[str, Any] = {}
        self.project_spec: Optional[Dict[str, Any]] = None
        self.backend_code: Optional[Dict[str, str]] = None
        self.integrated_project: Optional[str] = None
        self.zip_path: Optional[str] = None
        self.errors: list = []

class ProjectOrchestrator:
    """Orchestrates the entire project generation workflow"""
    
    def __init__(self, api_key: Optional[str] = None, logger: Optional[StreamlitLogger] = None):
        self.logger = logger or StreamlitLogger()
        # Use LLM with automatic fallback to Groq if OpenRouter fails
        self.llm = LLMWithFallback(api_key)
        
        # Initialize agents
        self.planner = PlannerAgent(self.llm, self.logger)
        self.backend_generator = BackendGeneratorAgent(self.llm, self.logger)
        self.integrator = IntegratorAgent(self.llm, self.logger)
        self.packager = PackagerAgent(self.llm, self.logger)
        self.github_publisher = GitHubPublisherAgent(self.llm, self.logger)
        
        # Build workflow graph
        self.workflow = self._build_workflow()
    
    def _build_workflow(self) -> StateGraph:
        """Build the LangGraph workflow"""
        workflow = StateGraph(dict)
        
        # Add nodes
        workflow.add_node("planner", self._planner_node)
        workflow.add_node("backend_generator", self._backend_generator_node)
        workflow.add_node("integrator", self._integrator_node)
        workflow.add_node("packager", self._packager_node)
        workflow.add_node("github_publisher", self._github_publisher_node)
        
        # Define edges
        workflow.set_entry_point("planner")
        workflow.add_edge("planner", "backend_generator")
        workflow.add_edge("backend_generator", "integrator")
        workflow.add_edge("integrator", "packager")
        workflow.add_edge("packager", "github_publisher")
        workflow.add_edge("github_publisher", END)
        
        return workflow.compile()
    
    def generate_project(self, project_config: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a complete project from config"""
        self.logger.log("🚀 Starting project generation workflow...")
        
        # Initialize state
        state = {
            "project_config": project_config,
            "project_spec": None,
            "backend_code": None,
            "integrated_project": None,
            "zip_path": None,
            "errors": []
        }
        
        try:
            # Run workflow
            self.logger.log("🔄 Starting LLM-powered project generation workflow...")
            final_state = self.workflow.invoke(state)
            
            # Validate that we got LLM-generated content, not fallbacks
            if not final_state.get("project_spec"):
                raise Exception("Project specification was not generated by LLM")
            if not final_state.get("backend_code") or len(final_state.get("backend_code", {})) < 3:
                raise Exception("Backend code was not properly generated by LLM")
            
            self.logger.log("✅ Project generation completed successfully with LLM-generated code!")
            
            return {
                "project_path": final_state.get("zip_path"),
                "project_directory": final_state.get("integrated_project"),
                "project_spec": final_state.get("project_spec"),
                "github_result": final_state.get("github_result"),
                "success": True
            }
        except Exception as e:
            self.logger.log(f"❌ Error in workflow: {str(e)}", level="error")
            self.logger.log("💡 Tip: Make sure your OpenRouter API key is set and working, or upgrade your account for more credits")
            raise
    
    def _planner_node(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Planner agent node"""
        self.logger.log("📋 Planning project architecture...")
        spec = self.planner.create_spec(state["project_config"])
        return {**state, "project_spec": spec}
    
    def _backend_generator_node(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Backend generator agent node"""
        self.logger.log("🔧 Generating backend code...")
        backend_code = self.backend_generator.generate(
            state["project_spec"],
            state["project_config"]["backend_stack"]
        )
        return {**state, "backend_code": backend_code}
    
    def _integrator_node(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Integrator agent node"""
        self.logger.log("🔗 Integrating frontend and backend...")
        project_path = self.integrator.integrate(
            state["project_config"],
            state["backend_code"],
            state["project_spec"]
        )
        return {**state, "integrated_project": project_path}
    
    def _packager_node(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Packager agent node"""
        self.logger.log("📦 Packaging project...")
        zip_path = self.packager.package(
            state["integrated_project"],
            state["project_config"]["project_name"]
        )
        return {**state, "zip_path": zip_path}
    
    def _github_publisher_node(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """GitHub publisher agent node"""
        self.logger.log("🐙 Publishing to GitHub...")
        # Allow runtime token override
        token = state["project_config"].get("github_token")
        if token:
            os.environ["GITHUB_ACCESS_TOKEN"] = token
        github_result = self.github_publisher.publish(
            state["project_config"],
            state["integrated_project"]
        )
        return {**state, "github_result": github_result}

